---
- ros_topic_name: "/antobot/robot/cmd_vel"
  gz_topic_name: "/model/antobot_ant/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/antobot/robot/odometry_sim"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/antobot_ant/scan/left"
  gz_topic_name: "/antobot_ant/scan/left"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/antobot_ant/scan/right"
  gz_topic_name: "/antobot_ant/scan/right"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/antobot_ant/scan/left/points"
  gz_topic_name: "/antobot_ant/scan/left/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
- ros_topic_name: "/antobot_ant/scan/right/points"
  gz_topic_name: "/antobot_ant/scan/right/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
# not in need of it when using ros2 control  
# - ros_topic_name: "/joint_states_sim"
#   gz_topic_name: "/world/lboro_nfl/model/antobot_ant/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/antobot_ant/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/antobot_ant/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/antobot_gps_sim"
  gz_topic_name: "/world/lboro_nfl/model/antobot_ant/link/base_link/sensor/gps_sensor/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS
- ros_topic_name: "/imu/data"
  gz_topic_name: "/world/lboro_nfl/model/antobot_ant/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

